#! /bin/bash

for directories in */ ; do
		while IFS=:" - " read -ra ADDR; do
			if [ ${#ADDR[@]} -eq 2 ]
			then
				echo "artist: ${ADDR[0]}"
				echo "album: ${ADDR[1]}"
			else 
				echo "doesn't match:  ${ADDR[0]}"
			fi
			
		done <<< "$directories"
done
